name: Alonso Vazquez Tena - Remote Updates via GitHub Actions

on:
    push:
         branches:
             - main


jobs:
   Explore-Github-Actions:
         runs-on: ubuntu-latest

         steps:
             - name: Start of the RemoteLopes Job
                run: echo "${{ github.actor }} is testing remote updates with RPI5"

             - name: Display Event information
                run:  |
                    echo "This job was triggered by ${{ github.event_name }} event."
                    echo "The name of the branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

             - name: Check out Repository code
                uses: actions/checkout@v4
